### PR TITLE
add index.d.ts

### PR DESCRIPTION
**Pull request by sinotaotao**
It's strange that the expression `expectError(baseUrl());` passed the tests. But I think it's ok to this extension

### CODE REVIEW

**Comment by UziTech** [comment]
looks like you have to run `npm install`

**Comment by sinotaotao** [comment]
Compared the code files to marked-highlight project, I haven't push packages-lock.json file up to repo.

**Review by UziTech — CHANGES_REQUESTED** [review]
Cna you add TestTypes to github actions like https://github.com/markedjs/marked-highlight/pull/35/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3

**Comment by sinotaotao** [comment]
> Cna you add TestTypes to github actions like https://github.com/markedjs/marked-highlight/pull/35/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3

Threre is only one function exported from this module, and the tsd not really execute the marked extension. I think the type check is enough here. There is a hug wall, I often cannot connect to Github.

**Comment by UziTech** [comment]
We just want to make sure tsd gets called on every PR so there are no regressions. I will get to it when I can.

**Review by UziTech — APPROVED** [review]
Thanks! :100:

**Pull request merged**
